Added register command
Real-Dev-Squad/discord-service pull request #18
Opened 2024-10-29 04:02 UTC by joyguptaa

Date: 29 Oct 2024

Developer Name: Joy Gupta

---

- https://github.com/Real-Dev-Squad/discord-service/issues/14

## Description

This PR will enable you to register your commands within discord

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<img width="688" alt="Screenshot 2024-10-29 at 9 27 34 AM" src="https://github.com/user-attachments/assets/813ab747-8301-415a-84f2-d44bec75395e">

<img width="1001" alt="Screenshot 2024-10-29 at 9 30 59 AM" src="https://github.com/user-attachments/assets/cb666cda-ca11-4ede-b6a4-c36cf1a5a06d">

## Test Coverage

<img width="1177" alt="Screenshot 2024-10-29 at 9 28 35 AM" src="https://github.com/user-attachments/assets/74613043-39b7-4a2a-985d-ac4c4c5c4cbd">

## Additional Notes

You may find few of the lines uncovered but those are discord's inbuilt method and cannot be tested

<img width="905" alt="Screenshot 2024-10-29 at 9 32 06 AM" src="https://github.com/user-attachments/assets/138c7d3d-1bc3-42b4-a164-f4be847f6e7b">

2024-10-29 20:08 UTC, yesyash commented on commands/main/register.go
> +var SetupConnection = func() {
- curious, why are we creating a function like this instead of `func SetupConnection`?

2024-10-29 20:08 UTC, yesyash commented on commands/main/register.go
> +	session, err = NewDiscord("Bot " + config.AppConfig.BOT_TOKEN)
- can we use the `:=` operator to create these variables, instead of declaring them individually?

2024-10-29 20:08 UTC, yesyash commented on commands/main/register.go
> +	defer openSession.close()
- please add a space after every block.

2024-10-31 02:48 UTC, joyguptaa commented on commands/main/register.go
> +	defer openSession.close()
done

2024-10-31 02:48 UTC, joyguptaa commented on commands/main/register.go
> +	session, err = NewDiscord("Bot " + config.AppConfig.BOT_TOKEN)
done

2024-10-31 02:48 UTC, joyguptaa commented on commands/main/register.go
> +var SetupConnection = func() {
Thanks for pointing it out. Actually we don't need SetupConnection function, logic can be moved into main itself

2024-10-31 19:20 UTC, prakashchoudhary07 commented
@joyguptaa We are creating a stateful bot right?

2024-11-01 07:17 UTC, joyguptaa commented
> @joyguptaa We are creating a stateful bot right?

Right, this is netHTTP server

2024-11-04 16:53 UTC, vinit717 commented on commands/main/register.go
Can you add tests in seprate folder

2024-11-04 18:31 UTC, joyguptaa commented on commands/main/register.go
That way, it won't be considered as a part of test coverage.

2024-11-04 18:36 UTC, vinit717 commented on commands/main/register.go
Why? do you know the reason

2024-11-04 18:42 UTC, joyguptaa commented on commands/main/register.go
> Moving tests to a separate /tests directory in Go can affect how code coverage is calculated and reported by go test. When test files are outside the package they are testing, coverage reporting does not automatically associate them with the source package.

2024-11-04 18:51 UTC, vinit717 approved these changes

2024-11-04 19:27 UTC, prakashchoudhary07 requested changes

2024-11-04 19:27 UTC, prakashchoudhary07 commented on commands/main/resgister_test.go
> +	})
If open() is implemented? then will it panic?

2024-11-04 19:27 UTC, prakashchoudhary07 commented on commands/main/resgister_test.go
> +	})
here also, text says, should always implement
But in tests its panics?

2024-11-04 19:27 UTC, prakashchoudhary07 commented on commands/main/resgister_test.go
> +	})
what are we checking here?

2024-11-04 19:41 UTC, joyguptaa commented on commands/main/resgister_test.go
> +	})
It will always panic in tests. Reason being we are not passing actual bot token and server id during tests. The purpose of these types of tests is to make sure that `open` method from  sessionWrapper should always be implemented

2024-11-04 19:41 UTC, joyguptaa commented on commands/main/resgister_test.go
> +	})
same reason as mentioned above

2024-11-04 19:44 UTC, joyguptaa commented on commands/main/resgister_test.go
> +	})
removed it, as it was not making sense

2024-11-05 02:41 UTC, prakashchoudhary07 commented on commands/main/resgister_test.go
> +	})
didn't get it

2024-11-05 02:42 UTC, prakashchoudhary07 commented on commands/main/resgister_test.go
> +	})
In the test name, it says, that some functions should be preset.
And in check we check for error?
I didn't quite understand what are we doing here?

2024-11-05 06:39 UTC, joyguptaa commented on commands/main/resgister_test.go
> +	})
To apply an assertion on the open method that it should always exists, I added this tests. Now why I am checking if it panics or not, is because while calling this function in tests, I am not passing it a valid connection, that is the reason it panics. Also "should panic when open() is called" is not the test name, you will see this string only if the test fails.

2024-11-05 17:24 UTC, merged