Feat : Added github workflow
Real-Dev-Squad/discord-service pull request #22
Opened 2024-11-12 18:53 UTC by joyguptaa

Date: 13 Nov 2024

Developer Name: Joy Gupta

---

## Issue Ticket Number
- https://github.com/Real-Dev-Squad/discord-service/issues/4

## Description

This PR contains github workflows

### Documentation Updated?

- [x] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

2024-11-13 03:01 UTC, prakashchoudhary07 requested changes

2024-11-13 03:01 UTC, prakashchoudhary07 commented on .github/workflows/ci.yml
> +        uses: actions/checkout@v3
Please use latest version's

2024-11-14 17:33 UTC, joyguptaa commented on .github/workflows/ci.yml
> +        uses: actions/checkout@v3
done

2024-11-15 05:06 UTC, joyguptaa commented on .github/workflows/ci.yml
> +      - 'develop'
No @prakashchoudhary07 
The reason why I specified main and develop under push is because I think we should run the CI checks once a PR gets merged into either of these branches.

2024-11-16 10:17 UTC, prakashchoudhary07 approved these changes

2024-11-16 10:27 UTC, merged